/* SPDX-License-Identifier: GPL-2.0-only */
/* Copyright (c) 2015, 2017, 2019, The Linux Foundation. All rights reserved. */
/* Copyright (c) 2022, Qualcomm Innovation Center, Inc. All rights reserved. */

#ifndef __QCOM_RPM_SMD_REGULATOR_H
#define __QCOM_RPM_SMD_REGULATOR_H

/* custom regulator table, undervolt */
#define RPM_SMD_REGULATOR_LEVEL_NONE		0
#define RPM_SMD_REGULATOR_LEVEL_RETENTION	8
#define RPM_SMD_REGULATOR_LEVEL_RETENTION_PLUS	16
#define RPM_SMD_REGULATOR_LEVEL_MIN_SVS		32
#define RPM_SMD_REGULATOR_LEVEL_LOW_SVS		48
#define RPM_SMD_REGULATOR_LEVEL_SVS		64
#define RPM_SMD_REGULATOR_LEVEL_SVS_PLUS	128
#define RPM_SMD_REGULATOR_LEVEL_NOM		192
#define RPM_SMD_REGULATOR_LEVEL_NOM_PLUS	256
#define RPM_SMD_REGULATOR_LEVEL_TURBO		320
#define RPM_SMD_REGULATOR_LEVEL_TURBO_NO_CPR	384
#define RPM_SMD_REGULATOR_LEVEL_SUPER_TURBO	416
#define RPM_SMD_REGULATOR_LEVEL_BINNING		464


#endif
